/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminTiersRouteImport } from './routes/_admin/admin.tiers'
import { Route as AdminAdminShiftsRouteImport } from './routes/_admin/admin.shifts'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin.settings'
import { Route as AdminAdminRevenueRouteImport } from './routes/_admin/admin.revenue'
import { Route as AdminAdminPcsRouteImport } from './routes/_admin/admin.pcs'
import { Route as AdminAdminMemberTopupRouteImport } from './routes/_admin/admin.member-topup'
import { Route as AdminAdminExpensesRouteImport } from './routes/_admin/admin.expenses'
import { Route as AdminAdminCashiersRouteImport } from './routes/_admin/admin.cashiers'
import { Route as AdminAdminAvailabilityRouteImport } from './routes/_admin/admin.availability'
import { Route as AdminAdminBookingsIndexRouteImport } from './routes/_admin/admin.bookings.index'
import { Route as AdminAdminBookingsNewRouteImport } from './routes/_admin/admin.bookings.new'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminTiersRoute = AdminAdminTiersRouteImport.update({
  id: '/admin/tiers',
  path: '/admin/tiers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminShiftsRoute = AdminAdminShiftsRouteImport.update({
  id: '/admin/shifts',
  path: '/admin/shifts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminRevenueRoute = AdminAdminRevenueRouteImport.update({
  id: '/admin/revenue',
  path: '/admin/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPcsRoute = AdminAdminPcsRouteImport.update({
  id: '/admin/pcs',
  path: '/admin/pcs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminMemberTopupRoute = AdminAdminMemberTopupRouteImport.update({
  id: '/admin/member-topup',
  path: '/admin/member-topup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminExpensesRoute = AdminAdminExpensesRouteImport.update({
  id: '/admin/expenses',
  path: '/admin/expenses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCashiersRoute = AdminAdminCashiersRouteImport.update({
  id: '/admin/cashiers',
  path: '/admin/cashiers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAvailabilityRoute = AdminAdminAvailabilityRouteImport.update({
  id: '/admin/availability',
  path: '/admin/availability',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBookingsIndexRoute = AdminAdminBookingsIndexRouteImport.update({
  id: '/admin/bookings/',
  path: '/admin/bookings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBookingsNewRoute = AdminAdminBookingsNewRouteImport.update({
  id: '/admin/bookings/new',
  path: '/admin/bookings/new',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/unlock': typeof UnlockRoute
  '/admin/availability': typeof AdminAdminAvailabilityRoute
  '/admin/cashiers': typeof AdminAdminCashiersRoute
  '/admin/expenses': typeof AdminAdminExpensesRoute
  '/admin/member-topup': typeof AdminAdminMemberTopupRoute
  '/admin/pcs': typeof AdminAdminPcsRoute
  '/admin/revenue': typeof AdminAdminRevenueRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/shifts': typeof AdminAdminShiftsRoute
  '/admin/tiers': typeof AdminAdminTiersRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/bookings/new': typeof AdminAdminBookingsNewRoute
  '/admin/bookings/': typeof AdminAdminBookingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unlock': typeof UnlockRoute
  '/admin/availability': typeof AdminAdminAvailabilityRoute
  '/admin/cashiers': typeof AdminAdminCashiersRoute
  '/admin/expenses': typeof AdminAdminExpensesRoute
  '/admin/member-topup': typeof AdminAdminMemberTopupRoute
  '/admin/pcs': typeof AdminAdminPcsRoute
  '/admin/revenue': typeof AdminAdminRevenueRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/shifts': typeof AdminAdminShiftsRoute
  '/admin/tiers': typeof AdminAdminTiersRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/bookings/new': typeof AdminAdminBookingsNewRoute
  '/admin/bookings': typeof AdminAdminBookingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/_admin/admin/availability': typeof AdminAdminAvailabilityRoute
  '/_admin/admin/cashiers': typeof AdminAdminCashiersRoute
  '/_admin/admin/expenses': typeof AdminAdminExpensesRoute
  '/_admin/admin/member-topup': typeof AdminAdminMemberTopupRoute
  '/_admin/admin/pcs': typeof AdminAdminPcsRoute
  '/_admin/admin/revenue': typeof AdminAdminRevenueRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/shifts': typeof AdminAdminShiftsRoute
  '/_admin/admin/tiers': typeof AdminAdminTiersRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/bookings/new': typeof AdminAdminBookingsNewRoute
  '/_admin/admin/bookings/': typeof AdminAdminBookingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unlock'
    | '/admin/availability'
    | '/admin/cashiers'
    | '/admin/expenses'
    | '/admin/member-topup'
    | '/admin/pcs'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/shifts'
    | '/admin/tiers'
    | '/admin/'
    | '/admin/bookings/new'
    | '/admin/bookings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unlock'
    | '/admin/availability'
    | '/admin/cashiers'
    | '/admin/expenses'
    | '/admin/member-topup'
    | '/admin/pcs'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/shifts'
    | '/admin/tiers'
    | '/admin'
    | '/admin/bookings/new'
    | '/admin/bookings'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/unlock'
    | '/_admin/admin/availability'
    | '/_admin/admin/cashiers'
    | '/_admin/admin/expenses'
    | '/_admin/admin/member-topup'
    | '/_admin/admin/pcs'
    | '/_admin/admin/revenue'
    | '/_admin/admin/settings'
    | '/_admin/admin/shifts'
    | '/_admin/admin/tiers'
    | '/_admin/admin/'
    | '/_admin/admin/bookings/new'
    | '/_admin/admin/bookings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/tiers': {
      id: '/_admin/admin/tiers'
      path: '/admin/tiers'
      fullPath: '/admin/tiers'
      preLoaderRoute: typeof AdminAdminTiersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/shifts': {
      id: '/_admin/admin/shifts'
      path: '/admin/shifts'
      fullPath: '/admin/shifts'
      preLoaderRoute: typeof AdminAdminShiftsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/revenue': {
      id: '/_admin/admin/revenue'
      path: '/admin/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminAdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/pcs': {
      id: '/_admin/admin/pcs'
      path: '/admin/pcs'
      fullPath: '/admin/pcs'
      preLoaderRoute: typeof AdminAdminPcsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/member-topup': {
      id: '/_admin/admin/member-topup'
      path: '/admin/member-topup'
      fullPath: '/admin/member-topup'
      preLoaderRoute: typeof AdminAdminMemberTopupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/expenses': {
      id: '/_admin/admin/expenses'
      path: '/admin/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AdminAdminExpensesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/cashiers': {
      id: '/_admin/admin/cashiers'
      path: '/admin/cashiers'
      fullPath: '/admin/cashiers'
      preLoaderRoute: typeof AdminAdminCashiersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/availability': {
      id: '/_admin/admin/availability'
      path: '/admin/availability'
      fullPath: '/admin/availability'
      preLoaderRoute: typeof AdminAdminAvailabilityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/bookings/': {
      id: '/_admin/admin/bookings/'
      path: '/admin/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminAdminBookingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/bookings/new': {
      id: '/_admin/admin/bookings/new'
      path: '/admin/bookings/new'
      fullPath: '/admin/bookings/new'
      preLoaderRoute: typeof AdminAdminBookingsNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminAvailabilityRoute: typeof AdminAdminAvailabilityRoute
  AdminAdminCashiersRoute: typeof AdminAdminCashiersRoute
  AdminAdminExpensesRoute: typeof AdminAdminExpensesRoute
  AdminAdminMemberTopupRoute: typeof AdminAdminMemberTopupRoute
  AdminAdminPcsRoute: typeof AdminAdminPcsRoute
  AdminAdminRevenueRoute: typeof AdminAdminRevenueRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminShiftsRoute: typeof AdminAdminShiftsRoute
  AdminAdminTiersRoute: typeof AdminAdminTiersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminBookingsNewRoute: typeof AdminAdminBookingsNewRoute
  AdminAdminBookingsIndexRoute: typeof AdminAdminBookingsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAvailabilityRoute: AdminAdminAvailabilityRoute,
  AdminAdminCashiersRoute: AdminAdminCashiersRoute,
  AdminAdminExpensesRoute: AdminAdminExpensesRoute,
  AdminAdminMemberTopupRoute: AdminAdminMemberTopupRoute,
  AdminAdminPcsRoute: AdminAdminPcsRoute,
  AdminAdminRevenueRoute: AdminAdminRevenueRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminShiftsRoute: AdminAdminShiftsRoute,
  AdminAdminTiersRoute: AdminAdminTiersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminBookingsNewRoute: AdminAdminBookingsNewRoute,
  AdminAdminBookingsIndexRoute: AdminAdminBookingsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
